# Use an official Nginx image to serve static files
FROM nginx:alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy a custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d

# Copy static files (HTML, CSS, JS) into the Nginx web server directory
COPY ./static /usr/share/nginx/html/static
COPY ./templates /usr/share/nginx/html/templates

# Expose port 80 for the frontend
EXPOSE 80
