version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-back
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-front
    ports:
      - "80:80"
